auto: true

markdown: kramdown
pygments: true
paginate: 8
permalink: /:title

title: Alick's Blog
url: http://blog.alickguo.me
feed: /atom.xml
author_info: <a href="http://blog.alickguo.me/">Alick's Blog</a>
