auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Alick's Blog
url: http://blog.a1ickgu0.me
feed: /atom.xml
author_info: <a href="http://blog.a1ickgu0.me/">Alick's Blog</a>
